// src/lib/Experience.svelte
<script lang="ts">
	import { marked } from 'marked';
	import type { Project, Technology } from './projects';

	interface Props {
		project: Project;
		minHeight?: number;
	}

	let { project, minHeight }: Props = $props();

	const html = $derived(marked.parse(project.text, { async: false }) as string);

	function formatTech(tech: Technology): string {
		switch (tech) {
			case 'vue':
				return 'VueJS';
			case 'svg':
				return 'SVG';
			case 'node':
				return 'Node.js';
			case 'opengl':
				return 'OpenGL';
			case 'mongo':
				return 'MongoDB';
			case 'pwa':
				return 'PWA';
			case 'graphql':
				return 'GraphQL';
			case 'nest':
				return 'NestJS';
			default:
				return tech[0].toUpperCase() + tech.slice(1);
		}
	}

	const technologies = $derived(project.technologies?.map(formatTech).join(', '));
</script>

<svelte:element
	this={project.link ? 'a' : 'div'}
	href={project.link}
	target={project.link ? '_blank' : undefined}
	rel={project.link ? 'noopener noreferrer' : undefined}
	class="block overflow-hidden rounded-lg border border-neutral-200 bg-white shadow-sm transition-shadow hover:shadow-md"
	style={minHeight ? `min-height: ${minHeight}px` : undefined}
>
	<div class="flex items-center gap-4 px-4 pt-4">
		{#if project.avatar || project.icon}
			<div
				class="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-full bg-neutral-50 text-2xl"
			>
				{#if project.avatar}
					{project.avatar}
				{:else if project.icon}
					<img src={project.icon} alt="" class="h-full w-full object-contain" />
				{/if}
			</div>
		{/if}
		<div>
			<h2 class="text-xl font-medium leading-snug">{project.title}</h2>
			<p class="text-sm text-neutral-500">{project.years}</p>
		</div>
	</div>

	{#if project.image}
		<img src={project.image} alt={project.title} class="mt-4 h-48 w-full object-cover" />
	{/if}

	<div class="prose-sm px-4 py-4 text-neutral-700 [&_p]:mb-2">
		<!-- eslint-disable-next-line svelte/no-at-html-tags -->
		{@html html}
		{#if technologies}
			<p class="mt-2 text-sm text-neutral-500">
				Technologies: {technologies}
			</p>
		{/if}
	</div>
</svelte:element>

// components/Experience.vue
<template>
  <v-card :href="project.link" target="blank">
    <v-list-item>
      <v-list-item-avatar v-if="project.avatar || project.icon" color="white">
        <template v-if="project.avatar">
          {{ project.avatar }}
        </template>
        <img v-else :src="project.icon" />
      </v-list-item-avatar>
      <v-list-item-content>
        <v-list-item-title class="headline">
          {{ project.title }}
        </v-list-item-title>
        <v-list-item-subtitle>{{ project.years }}</v-list-item-subtitle>
      </v-list-item-content>
    </v-list-item>
    <v-img v-if="project.image" :src="project.image" height="194" />
    <v-card-text>
      <p v-html="marked(project.text)" />
      <template v-if="project.technologies">
        Technologies:
        {{ project.technologies.map((tech) => formatTech(tech)).join(", ") }}
      </template>
    </v-card-text>
  </v-card>
</template>
<script lang="ts">
import { Vue, Component, Prop } from "vue-property-decorator";
import marked from "marked";
import { Project, Technology } from "../data/projects";

@Component
export default class Experience extends Vue {
  @Prop()
  project!: Project;

  formatTech(tech: Technology) {
    switch (tech) {
      case "vue":
        return "VueJS";
      case "svg":
        return "SVG";
      case "node":
        return "Node.js";
      case "opengl":
        return "OpenGL";
      case "mongo":
        return "MongoDB";
      case "pwa":
        return "PWA";
      case "graphql":
        return "GraphQL";
      case "nest":
        return "NestJS";
      default:
        return tech[0].toUpperCase() + tech.slice(1);
    }
  }

  marked = marked;
}
</script>
